SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_COLOUR = "white"
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_BOUNCE_RATIO = 1.3
ASTEROID_MAX_BOUNCE = 7

BACKGROUND_COLOUR = "black"

PLAYER_RADIUS = 20
PLAYER_COLOUR = "white"
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_JUMP_COOLDOWN = 0.5
PLAYER_JUMP_RATIO = 5

SHOT_RADIUS = 5
SHOT_COLOUR = "white"

LEVEL_RATIO = 30000

POWERUP_COLOUR = "red"